/* 
  Sketch generated by the Arduino IoT Cloud Thing "TechTalkies"

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  float dHT11;
  int position;
  bool lEDButton;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"
#include <Servo.h>
#include "DHT.h"

Servo myservo;

#define DHTTYPE DHT11   // DHT 11                     
#define DHTPIN 3     // Digital pin connected to the DHT sensor                     
DHT dht(DHTPIN, DHTTYPE);   
float tempCelsius;    // temperature in Celsius

unsigned long currentMillis;
const unsigned long delayPeriod = 1000;

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();

  pinMode(2, OUTPUT);
  myservo.attach(9);
  dht.begin();           // initialize the DHT sensor    
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  if (millis() - currentMillis >= delayPeriod)  //test whether the period has elapsed
  {
    float t = dht.readTemperature();
    dHT11 = t;
    currentMillis = millis();  //get the current "time" 
  }
  
}

/*
  Since LEDButton is READ_WRITE variable, onLEDButtonChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onLEDButtonChange()  {
  // Add your code here to act upon LEDButton change
  if(lEDButton == 1)
    digitalWrite(2, 1);
  else if(lEDButton == 0)
    digitalWrite(2, 0);
}

/*
  Since Position is READ_WRITE variable, onPositionChange() is
  executed every time a new value is received from IoT Cloud.
*/
void onPositionChange()  {
  // Add your code here to act upon Position change
  myservo.write(position);
}
